# Generated by Django 3.0.2 on 2020-02-17 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=255, verbose_name='系统名称')),
                ('fetch_method', models.CharField(max_length=255, verbose_name='查询方法')),
                ('table_name', models.CharField(max_length=255, verbose_name='表名')),
                ('primary_key', models.CharField(max_length=255, verbose_name='主键')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
                ('name', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='dictionary.ConfigSrc', verbose_name='数据源名称')),
            ],
            options={
                'verbose_name': '数据集管理',
                'verbose_name_plural': '数据集管理',
            },
        ),
    ]
