# Generated by Django 3.0.2 on 2020-02-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20200221_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configdata',
            name='sys_name',
            field=models.CharField(max_length=255, verbose_name='简称'),
        ),
    ]
