# Generated by Django 3.0.2 on 2020-02-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20200224_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configdata',
            options={'verbose_name': '数据集管理（测试返回数据用）', 'verbose_name_plural': '数据集管理（测试返回数据用）'},
        ),
        migrations.CreateModel(
            name='SystemProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=255, verbose_name='表名')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('top_level', models.CharField(max_length=255, verbose_name='')),
                ('second_level', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('third_level', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('fourth_level', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('note', models.TextField(verbose_name='摘要')),
                ('createtime', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('updatetime', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('configsrc', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='dictionary.ConfigSrc', verbose_name='数据源名称')),
            ],
            options={
                'verbose_name': 'Sys_Prod',
                'verbose_name_plural': 'Sys_Prod',
            },
        ),
    ]
