# Generated by Django 3.0.2 on 2020-02-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20200225_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemproduct',
            name='if_open',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否对外'),
        ),
    ]
