# Generated by Django 3.0.2 on 2020-02-26 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_systemproduct_if_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemproduct',
            options={'verbose_name': 'sys_product', 'verbose_name_plural': 'sys_product'},
        ),
        migrations.AlterField(
            model_name='systemproduct',
            name='fourth_level',
            field=models.CharField(blank=True, max_length=255, verbose_name='第四层级'),
        ),
        migrations.AlterField(
            model_name='systemproduct',
            name='second_level',
            field=models.CharField(blank=True, max_length=255, verbose_name='第二层级'),
        ),
        migrations.AlterField(
            model_name='systemproduct',
            name='third_level',
            field=models.CharField(blank=True, max_length=255, verbose_name='第三层级'),
        ),
        migrations.AlterField(
            model_name='systemproduct',
            name='top_level',
            field=models.CharField(max_length=255, verbose_name='第一层级'),
        ),
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.CharField(max_length=255, verbose_name='x_axis')),
                ('x_cn', models.CharField(max_length=255, verbose_name='x_cn')),
                ('y_axis', models.CharField(max_length=255, verbose_name='y_axis')),
                ('y_cn', models.CharField(max_length=255, verbose_name='y_cn')),
                ('z_axis', models.CharField(blank=True, max_length=255, verbose_name='z_axis')),
                ('z_cn', models.CharField(blank=True, max_length=255, verbose_name='z_cn')),
                ('unit', models.CharField(max_length=255, verbose_name='单位')),
                ('chart_type', models.CharField(max_length=255, verbose_name='图表类型')),
                ('time_cyc', models.CharField(max_length=255, verbose_name='周期')),
                ('chart_descrip', models.TextField(verbose_name='图表描述')),
                ('stat_way', models.TextField(verbose_name='统计方式')),
                ('note', models.TextField(verbose_name='备注')),
                ('read_field', models.TextField(max_length=255, verbose_name='执行语句')),
                ('status', models.IntegerField(choices=[(0, '停用'), (1, '可用')], default=1, verbose_name='可用状态')),
                ('createtime', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('updatetime', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('systemproduct', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='dictionary.SystemProduct', verbose_name='数据表名称')),
            ],
            options={
                'verbose_name': 'data_product',
                'verbose_name_plural': 'data_product',
            },
        ),
    ]
