# Generated by Django 3.0.2 on 2020-03-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_auto_20200226_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='节点名称')),
                ('parentID', models.IntegerField(verbose_name='父ID')),
                ('url', models.CharField(max_length=2000, verbose_name='链接')),
            ],
            options={
                'verbose_name': '菜单管理',
                'verbose_name_plural': '菜单管理',
            },
        ),
    ]
