# Generated by Django 3.0.2 on 2020-02-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dim_stock_updowns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_stock_code', models.CharField(max_length=255, verbose_name='灯塔代码')),
                ('week_ud', models.CharField(max_length=255, verbose_name='周涨跌幅')),
                ('month_ud', models.CharField(max_length=255, verbose_name='月涨跌幅')),
                ('three_month_ud', models.CharField(max_length=255, verbose_name='3月涨跌幅')),
                ('six_month_ud', models.CharField(max_length=255, verbose_name='6月涨跌幅')),
                ('year_ud', models.CharField(max_length=255, verbose_name='年涨跌幅')),
                ('update_time', models.CharField(max_length=255, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '涨跌幅',
                'verbose_name_plural': '涨跌幅',
            },
        ),
    ]
