# Generated by Django 3.0.2 on 2020-02-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App01DimStockUpdowns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_stock_code', models.CharField(blank=True, max_length=255, null=True)),
                ('week_ud', models.CharField(blank=True, max_length=255, null=True)),
                ('month_ud', models.CharField(blank=True, max_length=255, null=True)),
                ('three_month_ud', models.CharField(blank=True, max_length=255, null=True)),
                ('six_month_ud', models.CharField(blank=True, max_length=255, null=True)),
                ('year_ud', models.CharField(blank=True, max_length=255, null=True)),
                ('update_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '涨跌幅',
                'verbose_name_plural': '涨跌幅',
                'db_table': 'app01_dim_stock_updowns',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='dim_stock_updowns',
        ),
    ]
