# Generated by Django 3.0.2 on 2020-01-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200113_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='文章关键词'),
        ),
        migrations.AddField(
            model_name='article',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='top',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否推荐'),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
